"""
Control functions for all of the system test calls
"""
import LCPPistonConsole as lcpc

SMALL_VOLUME_MIN = 0.0
SMALL_VOLUME_MAX = 100.0

LARGE_VOLUME_MIN = 0.0
LARGE_VOLUME_MAX = 500.0

HOUSING_VOLUME = 1200.0

TOTAL_VOLUME_MIN = SMALL_VOLUME_MIN + LARGE_VOLUME_MIN + HOUSING_VOLUME
TOTAL_VOLUME_MAX = SMALL_VOLUME_MAX + LARGE_VOLUME_MAX + HOUSING_VOLUME

SMALL_PISTON_AREA = 33.3
LARGE_PISTON_AREA = 72.0


TOTAL_LENGTH_MIN = 0.0
TOTAL_LENGTH_MAX = 11.77

SMALL_LENGTH_MIN = 0.0
SMALL_LENGTH_MAX = 8.77

LARGE_LENGTH_MIN = 0.0
LARGE_LENGTH_MAX = 3.00

USER_PISTON_RATE_MIN = 0.001
USER_PISTON_RATE_MAX = 1.0