/*
 *  This file is automatically generated and does not require a license
 *
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *
 */
#include <stdint.h>
#include <driverlib/inc/hw_memmap.h>
#include <driverlib/eusci_a_uart.h>
#include <system/System.h>

/* USER CODE START (section: EUSCI_A1_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: EUSCI_A1_init_c_prologue) */

/*
 *  ======== EUSCI_A1_Init ========
 *  Initialize Config for the MSP430 EUSCI_A1
 */
void EUSCI_A1_Init(void)
{

    /* USER CODE START (section: EUSCI_A1_Init_prologue) */
    /* User initialization code */
    /* USER CODE END (section: EUSCI_A1_Init_prologue) */
  EUSCI_A_UART_initParam param = {
    .selectClockSource = EUSCI_A_UART_CLOCKSOURCE_SMCLK,
    .clockPrescalar = 17,
    .firstModReg = 0,
    .secondModReg = 74,
    .parity = EUSCI_A_UART_NO_PARITY,
    .msborLsbFirst = EUSCI_A_UART_LSB_FIRST,
    .numberofStopBits = EUSCI_A_UART_ONE_STOP_BIT,
    .uartMode = EUSCI_A_UART_MODE,
    .overSampling = 0
  };
  

    /* initialize UART for 115200 baud (based on a 2000000 Hz clock) */
    if (STATUS_FAIL == EUSCI_A_UART_init(EUSCI_A1_BASE, &param) ){
        return;
    }

    /* enable eUSCI UART */
    EUSCI_A_UART_enable(EUSCI_A1_BASE);

    /* set deglitch time */
    EUSCI_A_UART_selectDeglitchTime(EUSCI_A1_BASE, EUSCI_A_UART_DEGLITCH_TIME_200ns);

    /* disable eUSCI UART transmit interrupt */
    EUSCI_A_UART_disableInterrupt(EUSCI_A1_BASE, EUSCI_A_UART_TRANSMIT_INTERRUPT);

    /* enable eUSCI UART receive interrupt */
    EUSCI_A_UART_enableInterrupt(EUSCI_A1_BASE, EUSCI_A_UART_RECEIVE_INTERRUPT);

    /* USER CODE START (section: EUSCI_A1_Init_epilogue) */
    /* User code */
    /* USER CODE END (section: EUSCI_A1_Init_epilogue) */

}
