/*
 *  This file is automatically generated and does not require a license
 *
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 */
#include <stdint.h>
#include <driverlib/inc/hw_memmap.h>
#include <driverlib/eusci_a_uart.h>
#include <system/System.h>

/* USER CODE START (section: EUSCI_A1_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: EUSCI_A1_init_c_prologue) */

/*
 *  ======== EUSCI_A1_Init ========
 *  Initialize Config for the MSP430 EUSCI_A1
 */
void EUSCI_A1_Init(void)
{

    /* USER CODE START (section: EUSCI_A1_Init_prologue) */
    /* User initialization code */
    /* USER CODE END (section: EUSCI_A1_Init_prologue) */

    /* USER CODE START (section: EUSCI_A1_Init_epilogue) */
    /* User code */
    /* USER CODE END (section: EUSCI_A1_Init_epilogue) */

}
