/*
 *  This file is automatically generated and does not require a license
 *
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 */
#include <system/System.h>
#include <msp430fr5989.h>

   
   
__interrupt void Timer0_A0_ISR(void);
__interrupt void Timer0_A1_ISR(void);
__interrupt void TIMER2_A0_ISR(void);
__interrupt void TIMER2_A1_ISR(void);
__interrupt void TIMER3_A0_ISR(void);
__interrupt void UNMI_ISR(void);
__interrupt void RTC_ISR(void);
__interrupt void USCI_B0_ISR(void);
__interrupt void DMA_ISR(void);


/* USER CODE START (section: InterruptVectors_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_Init ========
 */
void InterruptVectors_Init(void)
{
}

/*
 *  ======== Timer0_A3 Interrupt Service Routine ======== 
 */
#pragma vector = TIMER0_A0_VECTOR
__interrupt void Timer0_A0_ISR(void)

{
    /* USER CODE START (section: TIMER0_A0_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: TIMER0_A0_ISR) */
}

/*
 *  ======== Timer0_A3 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_A1_VECTOR
__interrupt void Timer0_A1_ISR(void)
{
    /* USER CODE START (section: TIMER0_A1_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: TIMER0_A1_ISR) */
}


/*
 *  ======== Timer2_A2 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER2_A0_VECTOR
__interrupt void TIMER2_A0_ISR(void)
{
    /* USER CODE START (section: TIMER2_A0_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: TIMER2_A0_ISR) */
}

/*
 *  ======== Timer2_A2 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER2_A1_VECTOR
__interrupt void TIMER2_A1_ISR(void)
{
    /* USER CODE START (section: TIMER2_A1_ISR) */
//    P3OUT ^= BIT7;
    /* USER CODE END (section: TIMER2_A1_ISR) */

}


/*
 *  ======== Timer3_A2 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER3_A0_VECTOR
__interrupt void TIMER3_A0_ISR(void)
{
    /* USER CODE START (section: TIMER3_A0_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: TIMER3_A0_ISR) */
//  P3OUT ^= BIT7;
}



/*
 *  ======== User NMI Interrupt Service Routine ========
 *
 * Here are several important notes on using User NMI interrupt Handler:
 * 1. User could use the following code to efficiently service the interrupt
 *    handler. Just simply copy and paste it into your user definable code
 *    section.

    switch(__even_in_range(SYSUNIV, 4))
    {
        case SYSUNIV_NONE:   break;         // Vector  SYSUNIV_NONE:   No interrupt
        case SYSUNIV_NMIIFG: break;         // Vector  SYSUNIV_NMIIFG: NMIIFG
        case SYSUNIV_OFIFG:  break;         // Vector  SYSUNIV_OFIFG:  Osc. Fail - OFIFG
        default: break;
    }

 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=UNMI_VECTOR
__interrupt void UNMI_ISR(void)
{
    /* USER CODE START (section: UNMI_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: UNMI_ISR) */
}

/*
 *  ======== RTC Interrupt Service Routine ========
 *
 * Here are several important notes on using RTC interrupt Handler:
 * 1. User could use the following code to efficiently service the interrupt
 *    handler. Just simply copy and paste it into your user definable code
 *    section.

    switch (__even_in_range(RTCIV, 16)){
        case RTCIV_NONE: break;             //No interrupts pending
        case RTCIV_RTCRDYIFG:               //RTC ready: RTCRDYIFG
            // Occurs every second
            __no_operation();
            break;
        case RTCIV_RTCTEVIFG:               //RTC interval timer: RTCTEVIFG
            // Interrupts based on interval set in the event interrupt
            __no_operation();
            break;
        case RTCIV_RTCAIFG:                 //RTC user alarm: RTCAIFG
            // Interrupts based on the alarm interrupt
            __no_operation();
            break;
        case RTCIV_RT0PSIFG: break;         //RTC prescaler 0: RT0PSIFG
        case RTCIV_RT1PSIFG: break;         //RTC prescaler 1: RT1PSIFG
        case RTCIV_RTCOFIFG: break;         //RTC Oscillator fault
        default: break;
    }

 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=RTC_VECTOR
__interrupt void RTC_ISR(void)
{
    /* USER CODE START (section: RTC_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: RTC_ISR) */
}



/*
 *  ======== eUSCI_B0 Interrupt Service Routine ========
 */
#pragma vector=USCI_B0_VECTOR
__interrupt void USCI_B0_ISR(void)
{
    /* USER CODE START (section: USCI_B0_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: USCI_B0_ISR) */
}

/*
 *  ======== DMA Interrupt Service Routine ========
 */
#pragma vector=DMA_VECTOR
__interrupt void DMA_ISR(void)
{
    /* USER CODE START (section: DMA_ISR) */
    /* replace this comment with your code */
    /* USER CODE END (section: DMA_ISR) */
}
