/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti//_2_20_02_32/packages/ti/mcu/msp430/csl2/system/templates/System_5xx_init.xdt
 */
#include <driverlib/inc/hw_memmap.h>
#include <driverlib/sfr.h>
#include <system/System.h>

/* USER CODE START (section: System_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: System_init_c_prologue) */

/*
 *  ======== System_Init ========
 *  Initialize MSP430 Status Register
 */
void System_Init(void)
{
    /* USER CODE START (section: System_Init_prologue) */
    /* User initialization code */
    /* USER CODE END (section: System_Init_prologue) */

    /* 
     * SR, Status Register
     * 
     * ~SCG1 -- Disable System clock generator 1
     * ~SCG0 -- Disable System clock generator 0
     * ~OSCOFF -- Oscillator On
     * ~CPUOFF -- CPU On
     * GIE -- General interrupt enable
     * 
     * Note: ~<BIT> indicates that <BIT> has value zero
     */
    __bis_SR_register(GIE);

    /* USER CODE START (section: System_Init_epilogue) */
    /* User code */
    /* USER CODE END (section: System_Init_epilogue) */
}
